name: Stellar Expert WASM Release
on:
  push: 
    tags:
      - 'v*'  # triggered whenever a new tag (previxed with "v") is pushed to the repository
jobs:
  release-contract-governor:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Comet Factory Release'
      package: 'factory'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}

  release-contract-votes:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Comet Pool Release'
      package: 'contracts'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
